"""Backend refactor 2021/04

Revision ID: 1d6bbf31db0d
Revises: e4614ffaa6ae
Create Date: 2021-04-04 18:58:58.521560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d6bbf31db0d"
down_revision = "e4614ffaa6ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blocklist", schema=None) as batch_op:
        batch_op.alter_column("jti", existing_type=sa.VARCHAR(length=64), type_=sa.TEXT())

    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.alter_column("description", existing_type=sa.VARCHAR(length=128), type_=sa.TEXT())
        batch_op.alter_column("mail_to", existing_type=sa.VARCHAR(length=32), type_=sa.TEXT())
        batch_op.alter_column("name", existing_type=sa.VARCHAR(length=32), type_=sa.TEXT())
        batch_op.alter_column("uid", existing_type=sa.VARCHAR(length=6), type_=sa.TEXT())

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.alter_column("mail_from", new_column_name="smtp_mail_from", type_=sa.Text())
        batch_op.alter_column("smtp_host", existing_type=sa.VARCHAR(length=256), type_=sa.TEXT())
        batch_op.alter_column("mail_to", new_column_name="smtp_mail_to")
        batch_op.alter_column("smtp_pass", existing_type=sa.VARCHAR(length=128), type_=sa.TEXT())
        batch_op.alter_column("ssl_tls", new_column_name="smtp_ssl_tls", type_=sa.Boolean())
        batch_op.alter_column("starttls", new_column_name="smtp_starttls", type_=sa.Boolean())
        batch_op.drop_column("smtp_status")
        batch_op.alter_column("smtp_user", existing_type=sa.VARCHAR(length=128), type_=sa.TEXT())

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("password_hash", existing_type=sa.VARCHAR(length=95), type_=sa.TEXT())
        batch_op.alter_column("username", existing_type=sa.VARCHAR(length=128), type_=sa.TEXT())

    with op.batch_alter_table("XSS", schema=None) as batch_op:
        batch_op.alter_column("client_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("data", existing_type=sa.TEXT(), nullable=False, server_default="{}")
        batch_op.alter_column("headers", existing_type=sa.TEXT(), nullable=False, server_default="{}")
        batch_op.alter_column("ip_addr", existing_type=sa.VARCHAR(length=15), type_=sa.TEXT(), nullable=False)
        batch_op.alter_column("timestamp", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("xss_type", existing_type=sa.VARCHAR(length=9), type_=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("XSS", schema=None) as batch_op:
        batch_op.alter_column("xss_type", type_=sa.VARCHAR(length=9), existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("timestamp", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("ip_addr", type_=sa.VARCHAR(length=15), existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("headers", existing_type=sa.TEXT(), nullable=True, server_default=None)
        batch_op.alter_column("data", existing_type=sa.TEXT(), nullable=True, server_default=None)
        batch_op.alter_column("client_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("username", type_=sa.VARCHAR(length=128), existing_type=sa.TEXT())
        batch_op.alter_column("password_hash", type_=sa.VARCHAR(length=95), existing_type=sa.TEXT())

    with op.batch_alter_table("settings", schema=None) as batch_op:

        batch_op.alter_column("smtp_user", type_=sa.VARCHAR(length=128), existing_type=sa.TEXT())
        batch_op.add_column(sa.Column("smtp_status", sa.BOOLEAN(), nullable=True))
        batch_op.alter_column("smtp_starttls", new_column_name="starttls", type_=sa.BOOLEAN())
        batch_op.alter_column("smtp_ssl_tls", new_column_name="ssl_tls", type_=sa.BOOLEAN())
        batch_op.alter_column("smtp_pass", type_=sa.VARCHAR(length=128), existing_type=sa.TEXT())
        batch_op.alter_column("smtp_mail_to", new_column_name="mail_to")
        batch_op.alter_column("smtp_mail_from", new_column_name="mail_from", type_=sa.VARCHAR(length=256))
        batch_op.alter_column("smtp_host", type_=sa.VARCHAR(length=256), existing_type=sa.TEXT())

    with op.batch_alter_table("client", schema=None) as batch_op:
        batch_op.alter_column("uid", type_=sa.VARCHAR(length=6), existing_type=sa.TEXT())
        batch_op.alter_column("name", type_=sa.VARCHAR(length=32), existing_type=sa.TEXT())
        batch_op.alter_column("mail_to", type_=sa.VARCHAR(length=32), existing_type=sa.TEXT())
        batch_op.alter_column("description", type_=sa.VARCHAR(length=128), existing_type=sa.TEXT())

    with op.batch_alter_table("blocklist", schema=None) as batch_op:
        batch_op.alter_column("jti", type_=sa.VARCHAR(length=64), existing_type=sa.TEXT())

    # ### end Alembic commands ###
