"""Settings refactor

Revision ID: 1d6bbf31db0d
Revises: e4614ffaa6ae
Create Date: 2021-04-04 18:58:58.521560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d6bbf31db0d"
down_revision = "e4614ffaa6ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("smtp_status")
        batch_op.alter_column("starttls", new_column_name="smtp_starttls", type_=sa.Boolean())
        batch_op.alter_column("ssl_tls", new_column_name="smtp_ssl_tls", type_=sa.Boolean())
        batch_op.alter_column("mail_from", new_column_name="smtp_mail_from", type_=sa.Text())
        batch_op.alter_column("mail_to", new_column_name="smtp_mail_to")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.alter_column("smtp_ssl_tls", new_column_name="ssl_tls", type_=sa.BOOLEAN())
        batch_op.alter_column("smtp_mail_to", new_column_name="mail_to")
        batch_op.alter_column("smtp_mail_from", new_column_name="mail_from", type_=sa.VARCHAR(length=256))
        batch_op.alter_column("smtp_starttls", new_column_name="starttls", type_=sa.BOOLEAN())
        batch_op.add_column(sa.Column("smtp_status", sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
